enum Constants {
  SET_SEARCH_TEXT = 'SET_SEARCH_TEXT',
  SET_CURRENT_PAGE = 'SET_CURRENT_PAGE',
  SET_ROWS_PER_PAGE = 'SET_ROWS_PER_PAGE',
  GET_PHOTOS_SUCCESS = 'GET_PHOTOS_SUCCESS',
  GET_PHOTOS_IS_LOADING = 'GET_PHOTOS_IS_LOADING',
  CLEAR_PHOTOS = 'CLEAR_PHOTOS',
}

export default Constants;
