enum Constants {
  SET_SEARCH_TEXT = 'SET_SEARCH_TEXT',
  GET_PHOTOS_SUCCESS = 'GET_PHOTOS_SUCCESS',
  GET_PHOTOS_IS_LOADING = 'GET_PHOTOS_IS_LOADING',
  GET_PHOTOS_HAS_ERROR = 'GET_PHOTOS_HAS_ERROR',
  CLEAR_PHOTOS = 'CLEAR_PHOTOS',
}

export default Constants;
